### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by queenofdexterity** [queenofdexterity/BingeFlix#1]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational components
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by s-pangburn** [comment]
Great work overall Areej! This is exceptionally polished for the first day in! Just a few niggling problems that need to be addressed before I can sign off for you to move on to your next feature:

- [ ] https://bingeflix.herokuapp.com/#/sdlfkjslkdfjlksdjfslkdj <-- This (or any other invalid url) should redirect to either login or the front page (sorry, just a convention we enforce, haha)
- [ ] There should be just a little bit of padding on the sides of the input fields of your session form.
- [ ] It asks for your email to sign up, then greets you using your email address, which is a little awkward. It's understandable since Netflix actually asks for your email, but you can get around this in three ways:
   - Changing the field from "Email" to "Username"
   - Adding a field for "Username" when signing up and keeping the email field
   - Slicing the email at "@"
- [ ] The text should be a little bigger. It's a little hard to read, and I'm sure older recruiters would appreciate it. I'm mostly referring to the error messages and the names of the input fields, but if everything in the session form were a little bigger it wouldn't hurt either. Up to you!

Again, awesome work! Keep this up, and I think you'll be in an excellent place with this come next week!

**Comment by s-pangburn** [comment]
- [ ] Make sure to update your wiki with your Heroku link! Also open an issue for Heroku hosting so that I can approve it and your milestones will display the feature as complete :)

Other than that, great work! That technically isn't an issue with this feature, so I'll mark this as complete! Feel free to move on to your first MVP when you're ready!
