### ISSUE TITLE
PA Review: Movies Index

### ISSUE THREAD

**Issue by queenofdexterity** [queenofdexterity/BingeFlix#3]
- [ ]  Users have a video feed of recommended videos
- [ ]  Adequate styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds to demonstrate the feature

**Comment by s-pangburn** [comment]
This looks awesome Areej! Great job! :)

- [ ] The movie preview image only shows up when you click directly on the text. Instead, it would be better if it showed up when you click anywhere on the div element (besides the play button, of course)
- [ ] You were already working on this when I arrived, so don't consider it high priority, like I said, but the text resizes a little janky when mousing over the movies on the index. This is really hard to perfect the CSS for, so I would say leave it for now and come back to it once your MVPs are finished. (Having the text fade in or pop in only once the animation is done might work? But that's just a guess on my part)
  - Alternatively, Anastassia suggested having the description keep a constant width so that it does animate at all? I'm not sure how that would look in practice though. Again, come back to this later or when you feel like it.
- [ ] Another very mild criticism, having a simple footer can help the site feel more "complete". The links don't have to lead anywhere. I had a student last cohort who had all their footer links go to their LinkedIn page :)

Overall, I would consider these to be minor points, so let's consider this feature more or less complete. Definitely fix the div clicking issue, but beyond that, just get around to the other two when you can!
