### ISSUE TITLE
PA Review: Play Videos

### ISSUE THREAD

**Issue by queenofdexterity** [queenofdexterity/BingeFlix#4]
- [ ] Users can watch videos
- [ ] Videos are of decent quality
- [ ] When playing, videos take up entire screen (when possible)
- [ ] Adequate styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds to demonstrate the feature

**Comment by s-pangburn** [comment]
I love your seed data, a few of these made me chuckle :) You misspelled "Buckingham" though, I think?

- [ ] Sometimes the arrow to go back to the previous page in your video player disappears after clicking a few of the controls of the video (skipping around, pausing and playing), I'm not sure why this happens, it might be an easy fix or a very, very hard fix. In the latter case, don't worry about it too much, but if it's an easy fix, please fix it.

Since it's not clear whether that's something actually actionable for you, I can go ahead and mark this issue as complete. Feel free to move on after looking into that issue for a little bit 🙂
