### ISSUE TITLE
PA Review: Add Movies to 'My List'

### ISSUE THREAD

**Issue by queenofdexterity** [queenofdexterity/BingeFlix#5]
- [x] Users can add movies to and delete movies from one of their "My Lists"
- [x] Users can delete movies from their lists
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by s-pangburn** [comment]
Looks good Areej! I understand you didn't have time to implement custom lists, but since that was just a suggestion, this still totally passes 🙂  Good work!

Feel free to return to that later if you ever feel like it, but it's not strictly necessary. I just think it would make the site a little more technically impressive, but you could pour that energy into your other projects as well and it'd be just as effective, so don't worry about it too much.
